name: поднятие таски

on:
  push:
    branches: [main, master, DevSecOps]
  pull_request:

permissions:
  security-events: write
  contents: read

jobs:
  sast:
    uses: ./.github/workflows/sast.yml

  sca:
    uses: ./.github/workflows/sca.yml
    secrets:
      NVD_API_KEY: ${{ secrets.NVD_API_KEY }}

  dast:
    needs: [sast, sca]
    if: always()
    uses: ./.github/workflows/dast.yml
