name: поднятие таски

on:
  push:
    branches: [main, master, DevSecOps]
  pull_request:

permissions:
  contents: read

jobs:
  sast:
    uses: ./.github/workflows/sast.yml

  sca:
    uses: ./.github/workflows/sca.yml
    secrets:
      NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
      OSSINDEX_USERNAME: ${{ secrets.OSSINDEX_USERNAME }}
      OSSINDEX_TOKEN: ${{ secrets.OSSINDEX_TOKEN }}

  dast:
    # needs: [sast, sca]
    uses: ./.github/workflows/dast.yml

  ui-tests:
    uses: ./.github/workflows/ui-tests.yml
