package com.example.backend.entity;

public enum BlockType {
    UML_CLASS, UML_INTERFACE, PROCESS_START, PROCESS_END, PROCESS_ACTION,
    PROCESS_DECISION, TEXT_BOX, NOTE, SHAPE_RECTANGLE, SHAPE_CIRCLE, CUSTOM
}